#cloud-config


package_update: true
package_upgrade: true

packages:
  - docker.io

users:
  - default
  - name: ubuntu
    gecos: ubuntu
    primary_group: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}

write_files:
  - path: /usr/local/bin/sc-startup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      apt-get update
      apt-get install docker.io
      systemctl docker start 
      usermod -a -G docker ubuntu
      docker stop $(docker ps -a -q)
      docker pull jhartway99/htmx-agario:latest
      docker run --restart=always --network=host -d jhartway99/htmx-agario:latest

  - path: /etc/systemd/system/sc.service 
    content: |
      [Unit]
      Description=Startup super chat

      [Service]
      ExecStart=/usr/local/bin/sc-startup.sh

      [Install]
      WantedBy=multi-user.target
  
runcmd:
  - systemctl enable docker.service
  - systemctl start docker.service
  - systemctl enable sc.service
  - systemctl start sc.service
