version: "3"



services:
  app:
    image: jhartway99/htmx-agario
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app
    build: ./
    network_mode: "host"

